### ISSUE TITLE
is dynamo too expensive?

### ISSUE THREAD

**Issue by marcusbesjes** [vigour-io/blend-state-dynamo#19]
### Throughput units

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ProvisionedThroughput.html
#### Read

If your items are smaller than 4 KB in size, each read capacity unit will yield one strongly consistent read per second or two eventually consistent reads per second.
- 2 property reads / second === 1 write capacity unit
#### Write

If your items are smaller than 1 KB in size, each write capacity unit will yield one write per second.
- 1 property write / second === 1 write capacity unit
#### Quick projection

quick n dirty calculation: timeline and snapshot table with 100 read/write for snapshot and 1 read / 100 w write for timeline table: $307.28 / month. In terms of write this is 50 concurrent users watching video (nothing else), in terms of read its harder to project, but a couple of logins / second would bust this limit is my guess. If this is an average over the entire month then it might not be super bad, but we should make a serious cost projection for sure.

**Comment by jimdebeer** [comment]
i think for now its fine, we wait until our boys from zeit finished some stuff for is (which is dirt cheap) then just go for that
