### ISSUE TITLE
[.load] handle max query chunk of 1MB

### ISSUE THREAD

**Issue by marcusbesjes** [vigour-io/blend-state-dynamo#20]
### Paginating the Results

`LastEvaluatedKey` > `ExclusiveStartKey`

DynamoDB paginates the results from Query and Scan operations. With pagination, Query and Scan results are divided into distinct pieces; an application can process the first page of results, then the second page, and so on. The data returned from a Query or Scan operation is limited to 1 MB; this means that if the result set exceeds 1 MB of data, you'll need to perform another Query or Scan operation to retrieve the next 1 MB of data.

If you query or scan for specific attributes that match values that amount to more than 1 MB of data, you'll need to perform another Query or Scan request for the next 1 MB of data. To do this, take the LastEvaluatedKey value from the previous request, and use that value as the ExclusiveStartKey in the next request. This approach will let you progressively query or scan for new data in 1 MB increments.

When the entire result set from a Query or Scan has been processed, LastEvaluatedKey is null. This indicates that the result set is complete (that is, the operation processed the “last page” of data).

If LastEvaluatedKey is anything other than null, this does not necessarily mean that there is more data in the result set. The only way to know when you have reached the end of the result set is when LastEvaluatedKey is null.

**Comment by mstdokumaci** [comment]
fixed in https://github.com/vigour-io/blend-state-dynamo/tree/feature/timeline
